"""Shared state model for the attribution chat agent.

Defines the Pydantic models that represent the mutable conversation state
shared between the PydanticAI agent (backend) and CopilotKit (frontend)
via the AG-UI protocol. State changes are serialised as ``StateSnapshot``
and ``StateDelta`` Server-Sent Events.

The frontend observes this state through CopilotKit's
``useCopilotReadable`` hooks, enabling real-time UI updates when the
agent sets ``current_work_id``, ``confidence_score``, or
``pending_correction``.

Classes
-------
AttributionAgentState
    Main state container with fields for the current work context,
    search state, and pending corrections.
CorrectionPreview
    Preview of a proposed field correction awaiting user approval.

See Also
--------
music_attribution.chat.agent : Agent that mutates this state.
music_attribution.chat.agui_endpoint : SSE endpoint that serialises this state.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class AttributionAgentState(BaseModel):
    """Shared state between the PydanticAI agent and CopilotKit frontend.

    Every field in this model is serialised as an AG-UI ``StateSnapshot``
    event after each agent turn. CopilotKit ``useCopilotReadable`` hooks
    on the frontend subscribe to individual fields for reactive UI
    updates (e.g. highlighting the current work, showing search counts).

    Agent tools mutate this state via ``ctx.deps.state`` during
    execution. The AG-UI endpoint serialises the final state at the
    end of each run.

    Attributes
    ----------
    current_work_id : str | None
        Attribution ID of the work currently being discussed. Set by
        ``explain_confidence`` and ``suggest_correction`` tools.
    current_work_title : str | None
        Display title of the current work for the frontend header.
    confidence_score : float | None
        Confidence score (0.0--1.0) currently under discussion.
        Constrained to [0.0, 1.0] via Pydantic validators.
    review_queue_size : int
        Number of works pending human review. Non-negative.
    pending_correction : CorrectionPreview | None
        Preview of a correction the agent is suggesting. The frontend
        renders this as a before/after diff. Cleared after feedback
        submission.
    explanation_text : str | None
        Agent's current natural-language explanation of a confidence
        score, displayed in the chat sidebar.
    last_search_query : str | None
        Most recent search query executed by the agent.
    last_search_count : int
        Number of results from the most recent search. Non-negative.
    """

    current_work_id: str | None = Field(
        default=None,
        description="Attribution ID of the work currently being discussed",
    )
    current_work_title: str | None = Field(
        default=None,
        description="Display title of the current work",
    )
    confidence_score: float | None = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Current confidence score being discussed",
    )
    review_queue_size: int = Field(
        default=0,
        ge=0,
        description="Number of works pending review",
    )
    pending_correction: CorrectionPreview | None = Field(
        default=None,
        description="Preview of a correction the agent is suggesting",
    )
    explanation_text: str | None = Field(
        default=None,
        description="Agent's current explanation text for confidence score",
    )
    last_search_query: str | None = Field(
        default=None,
        description="Last search query the agent executed",
    )
    last_search_count: int = Field(
        default=0,
        ge=0,
        description="Number of results from last search",
    )


class CorrectionPreview(BaseModel):
    """Preview of a proposed field correction before user approval.

    Generated by the ``suggest_correction`` agent tool and stored in
    ``AttributionAgentState.pending_correction``. The CopilotKit
    frontend renders this as a diff view (current vs. suggested value)
    with the agent's reasoning and confidence level.

    Attributes
    ----------
    field : str
        Name of the attribution record field being corrected
        (e.g. ``"role_detail"``, ``"artist_name"``).
    current_value : str
        Current value of the field in the attribution record.
    suggested_value : str
        Proposed replacement value.
    reason : str
        Agent's justification for the correction, displayed to the
        reviewer for informed approval/rejection.
    confidence_in_correction : float
        Agent's confidence in the suggested correction (0.0--1.0).
        Constrained to [0.0, 1.0] via Pydantic validators.
    """

    field: str = Field(description="Field being corrected")
    current_value: str = Field(description="Current value in the record")
    suggested_value: str = Field(description="Suggested new value")
    reason: str = Field(description="Why the agent suggests this correction")
    confidence_in_correction: float = Field(
        ge=0.0,
        le=1.0,
        description="Agent's confidence in the suggested correction",
    )
